definitions:
  models.AuthorizeRequest:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
  models.AuthorizeResponse:
    properties:
      is_authorize:
        type: boolean
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/auth/authorize:
    post:
      consumes:
      - application/json
      description: |-
        Получает логин и пароль пользователя,
        проверяет пользователя и возвращает true/false
      parameters:
      - description: Данные пользователя
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.AuthorizeRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.AuthorizeResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - auth
swagger: "2.0"
