services:
  db:
    image: postgres:15
    container_name: wishlist-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    networks:
      - wishlist-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    container_name: wishlist-redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --appendonly yes --bind 0.0.0.0
    restart: unless-stopped
    networks:
      - wishlist-network

  backend:
    container_name: wishlist-server
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "${SERVER_HOST_PORT}:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_HOST_PORT}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      PORT: ${SERVER_HOST_PORT}
      CLIENT_HOST: ${CLIENT_HOST}
      CLIENT_PORT: ${CLIENT_HOST_PORT}
      REDIS_PORT: ${REDIS_PORT}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_TTL: ${JWT_ACCESS_TTL}
      JWT_REFRESH_TTL: ${JWT_REFRESH_TTL}
    depends_on:
      - db
      - redis
    networks:
      - wishlist-network

  frontend:
    container_name: wishlist-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    environment:
      VITE_SERVER_HOST: ${SERVER_HOST}
      VITE_SERVER_PORT: ${SERVER_HOST_PORT}
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - wishlist-network

networks:
  wishlist-network:
    driver: bridge

volumes:
  db-data: