CREATE TABLE public.users
(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name character varying(150) NOT NULL,
    password_hash character varying(150) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    updated_at timestamp with time zone
);

CREATE TABLE public.groups
(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name character varying(300) NOT NULL,
    admin_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "group-admin" FOREIGN KEY (admin_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID
);

CREATE TABLE public.group_member
(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    group_id uuid NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT "gm-group" FOREIGN KEY (group_id)
        REFERENCES public.groups (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID,
    CONSTRAINT "gm-member" FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID
);

CREATE TABLE public.wishlists
(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name character varying(300) NOT NULL,
    group_id uuid NOT NULL,
    creator_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT NOW(),
    deleted_at timestamp with time zone,
    CONSTRAINT "wishlist-group" FOREIGN KEY (group_id)
        REFERENCES public.groups (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID,
    CONSTRAINT "wishlist-creator" FOREIGN KEY (creator_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID
);

CREATE TABLE public.statuses
(
    id INT GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME status_id_seq) PRIMARY KEY,
    description character varying(100) NOT NULL
);

CREATE TABLE public.entrys
(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    wishlist_id uuid NOT NULL,
    status_id INT NOT NULL DEFAULT 1,
    creator_id uuid NOT NULL,
    title character varying(300) NOT NULL,
    description text,
    CONSTRAINT "entry-wishlist" FOREIGN KEY (wishlist_id)
        REFERENCES public.wishlists (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID,
    CONSTRAINT "entry-creator" FOREIGN KEY (creator_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID,
    CONSTRAINT "entry-status" FOREIGN KEY (status_id)
        REFERENCES public.statuses (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
        NOT VALID
);